"use client";

import { useMemo, useState } from "react";
import { formatPrice, getEstimatedTotal, getNightlyPrice, getNights, getRoom, roomOptions, siteConfig, type RoomId } from "./site-data";

type FormState = { checkIn: string; checkOut: string; adults: number; children: number; extraBed: boolean; roomId: RoomId; parking: boolean; kitchen: boolean; comment: string; petsNotNeeded: boolean };
const initialForm: FormState = { checkIn: "2026-09-10", checkOut: "2026-09-13", adults: 2, children: 0, extraBed: false, roomId: "four-balcony", parking: true, kitchen: true, comment: "", petsNotNeeded: false };
const steps = ["Даты и гости", "Вариант", "Условия", "Итог"];

function formatDate(value: string) { return value ? new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long" }).format(new Date(`${value}T12:00:00`)) : "—"; }
function pluralize(value: number, one: string, few: string, many: string) { const mod10 = value % 10; const mod100 = value % 100; if (mod10 === 1 && mod100 !== 11) return one; if (mod10 >= 2 && mod10 <= 4 && (mod100 < 10 || mod100 >= 20)) return few; return many; }
function Icon({ symbol }: { symbol: string }) { return <span className="icon-mark" aria-hidden="true">{symbol}</span>; }

export default function Home() {
  const [step, setStep] = useState(1);
  const [form, setForm] = useState<FormState>(initialForm);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  const nights = useMemo(() => getNights(form.checkIn, form.checkOut), [form.checkIn, form.checkOut]);
  const guests = form.adults + form.children;
  const selectedRoom = getRoom(form.roomId);
  const total = useMemo(() => getEstimatedTotal(form.roomId, form.checkIn, form.checkOut), [form.roomId, form.checkIn, form.checkOut]);

  const updateForm = <K extends keyof FormState>(key: K, value: FormState[K]) => { setForm((current) => ({ ...current, [key]: value })); setError(""); };
  const goToBuilder = () => { document.getElementById("builder")?.scrollIntoView({ behavior: "smooth" }); setStep(1); };
  const validateStep = () => {
    if (step === 1) {
      if (!form.checkIn || !form.checkOut) return "Укажите даты заезда и выезда.";
      if (nights <= 0) return "Дата выезда должна быть позже даты заезда.";
      if (guests < siteConfig.limits.minGuests || guests > siteConfig.limits.maxGuests) return "Сейчас на странице можно подобрать размещение для 1–4 гостей.";
      if (form.adults < siteConfig.limits.minAdults) return "Нужен хотя бы один взрослый гость.";
    }
    if (step === 2 && !form.roomId) return "Выберите подходящий вариант.";
    if (step === 3 && !form.petsNotNeeded) return "Подтвердите, что размещение с домашними животными не требуется.";
    return "";
  };
  const nextStep = () => { const validationError = validateStep(); if (validationError) { setError(validationError); return; } setError(""); setStep((current) => Math.min(4, current + 1)); };
  const previousStep = () => { setError(""); setStep((current) => Math.max(1, current - 1)); };
  const message = `Здравствуйте! Хотим узнать наличие в “Постоялом дворе”.

Заезд: ${formatDate(form.checkIn)}
Выезд: ${formatDate(form.checkOut)}
Ночей: ${nights}
Гостей: ${form.adults} взрослых${form.children ? ` и ${form.children} ${pluralize(form.children, "ребёнок", "ребёнка", "детей")}` : ""}
Выбранный вариант: ${selectedRoom.title}
Дополнительное место: ${form.extraBed ? "да" : "нет"}
Парковка: ${form.parking ? "да" : "нет"}
Кухня: ${form.kitchen ? "да" : "нет"}${form.comment ? `
Комментарий: ${form.comment}` : ""}

Подскажите, пожалуйста, есть ли свободный вариант и какая будет актуальная стоимость проживания?`;
  const whatsappHref = `https://wa.me/${siteConfig.whatsappNumber}?text=${encodeURIComponent(message)}`;
  const copyMessage = async () => { try { await navigator.clipboard.writeText(message); setCopied(true); window.setTimeout(() => setCopied(false), 1800); } catch { setError("Не удалось скопировать текст. Вы можете выделить его вручную."); } };

  return <main>
    <header className="site-header"><a className="brand" href="#top" aria-label="Постоялый двор — в начало"><span className="brand-mark">ПД</span><span><strong>Постоялый двор</strong><small>Небуг · Приморская, 13А</small></span></a><a className="header-contact" href={`https://wa.me/${siteConfig.whatsappNumber}`} target="_blank" rel="noreferrer">WhatsApp <span aria-hidden="true">↗</span></a></header>

    <section className="hero section-shell" id="top"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> Частный сектор в Небуге</p><h1>Подберите номер в Небуге под свои даты и состав гостей</h1><p className="hero-lead">До моря около 200 метров. Кухня, парковка и варианты для 3–4 гостей. Оставьте готовый запрос — наличие и точную стоимость подтвердит хозяин.</p><div className="hero-actions"><button className="button button-primary" type="button" onClick={goToBuilder}>Подобрать номер <span aria-hidden="true">↓</span></button><a className="text-link" href="#conditions">Посмотреть условия <span aria-hidden="true">↘</span></a></div><div className="hero-facts" aria-label="Коротко об объекте"><span><b>200 м</b> до моря</span><span><b>Кухня</b> с посудой</span><span><b>Парковка</b> на территории</span><span><b>3–4</b> гостя</span></div></div><div className="hero-visual"><img src="/photos/object-02.png" alt="Зелёный двор и входы в номера «Постоялого двора»"/><div className="hero-photo-shade"/><div className="visual-copy"><span className="visual-index">Фото объекта</span><strong>Тихий ритм<br/>у моря</strong><small>Зелёный двор «Постоялого двора»</small></div><span className="visual-stamp">Небуг<br/><em>2026</em></span></div></section>

    <section className="builder-section" id="builder"><div className="section-shell"><div className="section-intro section-intro-builder"><div><p className="eyebrow"><span className="eyebrow-dot" /> Подбор проживания</p><h2>Соберите запрос за минуту</h2></div><p>Страница поможет сориентироваться по опубликованным ценам 2026 года. Свободные даты и итоговую стоимость всегда подтверждает владелец.</p></div><div className="stepper" aria-label="Шаги подбора">{steps.map((label, index) => { const number = index + 1; return <button key={label} className={`stepper-item ${step === number ? "is-active" : ""} ${step > number ? "is-done" : ""}`} type="button" onClick={() => number < step && setStep(number)} aria-current={step === number ? "step" : undefined}><span>{step > number ? "✓" : `0${number}`}</span><strong>{label}</strong></button>; })}</div>
      <div className="builder-card"><div className="builder-card-topline"><span>Шаг 0{step}</span><span>{step} из 4</span></div>
        {step === 1 && <div className="step-content"><div className="step-heading"><p className="eyebrow">Начнём с главного</p><h3>Когда и кто приезжает?</h3><p>Укажите даты и состав гостей — так мы покажем только подходящие варианты.</p></div><div className="form-grid form-grid-dates"><label className="field"><span>Заезд</span><input type="date" min="2026-06-01" value={form.checkIn} onChange={(event) => updateForm("checkIn", event.target.value)} /></label><label className="field"><span>Выезд</span><input type="date" min={form.checkIn || "2026-06-01"} value={form.checkOut} onChange={(event) => updateForm("checkOut", event.target.value)} /></label></div><div className="night-count"><Icon symbol="◷"/><strong>{nights || "—"}</strong> {nights ? pluralize(nights, "ночь", "ночи", "ночей") : "ночей"}</div><div className="guest-controls"><div className="guest-control"><div><strong>Взрослые</strong><small>от 18 лет</small></div><Counter value={form.adults} min={1} max={4} onChange={(value) => updateForm("adults", value)}/></div><div className="guest-control"><div><strong>Дети</strong><small>до 17 лет</small></div><Counter value={form.children} min={0} max={3} onChange={(value) => updateForm("children", value)}/></div></div><label className="switch-row"><span className={`switch ${form.extraBed ? "is-on" : ""}`}><input type="checkbox" aria-label="Нужно дополнительное место" checked={form.extraBed} onChange={(event) => updateForm("extraBed", event.target.checked)}/><i/></span><span><strong>Нужно дополнительное место</strong><small>Учтём это в сообщении владельцу</small></span></label></div>}
        {step === 2 && <div className="step-content"><div className="step-heading"><p className="eyebrow">Второй шаг</p><h3>Какой вариант подойдёт?</h3><p>Выберите ориентир. Если точного соответствия датам нет, сумма останется «уточняется».</p></div><div className="rooms-grid">{roomOptions.map((room) => { const disabled = guests > room.capacity; const selected = form.roomId === room.id; const roomTotal = room.id === "clarify" ? null : getEstimatedTotal(room.id, form.checkIn, form.checkOut); const price = room.id === "clarify" ? null : getNightlyPrice(room.id, form.checkIn); return <button className={`room-card ${selected ? "is-selected" : ""} ${disabled ? "is-disabled" : ""}`} type="button" key={room.id} onClick={() => !disabled && updateForm("roomId", room.id)} disabled={disabled} aria-pressed={selected}><span className="room-card-check">{selected ? "✓" : ""}</span><span className="room-eyebrow">{room.eyebrow}</span><strong className="room-title">{room.title}</strong><span className="room-capacity">до {room.capacity} {pluralize(room.capacity, "гостя", "гостей", "гостей")}</span><span className="room-features">{room.features.map((feature) => <em key={feature}>{feature}</em>)}</span><span className="room-note">{room.note}</span><span className="room-price">{formatPrice(price)} <small>за сутки</small></span><span className="room-total">{roomTotal !== null ? `${formatPrice(roomTotal)} за ${nights} ${pluralize(nights, "ночь", "ночи", "ночей")}` : "Ориентировочная стоимость уточняется"}</span><span className="room-disclaimer">Финальная цена подтверждается владельцем</span>{disabled && <span className="room-disabled">Не подходит по числу гостей</span>}</button>; })}</div></div>}
        {step === 3 && <div className="step-content"><div className="step-heading"><p className="eyebrow">Третий шаг</p><h3>Что важно учесть?</h3><p>Отметьте бытовые условия и оставьте комментарий, если нужно.</p></div><div className="conditions-grid"><Toggle checked={form.parking} onChange={(value) => updateForm("parking", value)} title="Нужна парковка" detail="Запросим место на территории" symbol="P"/><Toggle checked={form.kitchen} onChange={(value) => updateForm("kitchen", value)} title="Нужна кухня" detail="Кухня с посудой" symbol="K"/></div><label className="field field-comment"><span>Комментарий гостя <small>необязательно</small></span><textarea rows={4} value={form.comment} onChange={(event) => updateForm("comment", event.target.value)} placeholder="Например, важен тихий номер или поздний заезд"/></label><label className="checkbox-row"><input type="checkbox" aria-label="Размещение с домашними животными не требуется" checked={form.petsNotNeeded} onChange={(event) => updateForm("petsNotNeeded", event.target.checked)}/><span>Подтверждаю: размещение с домашними животными не требуется.</span></label></div>}
        {step === 4 && <div className="step-content"><div className="step-heading"><p className="eyebrow">Почти готово</p><h3>Проверьте запрос перед отправкой</h3><p>Мы не бронируем автоматически: сообщение откроется в WhatsApp, а наличие и точную стоимость подтвердит хозяин.</p></div><div className="summary-layout"><div className="summary-list"><SummaryRow label="Даты" value={`${formatDate(form.checkIn)} — ${formatDate(form.checkOut)}`}/><SummaryRow label="Гости" value={`${form.adults} взрослых${form.children ? `, ${form.children} ${pluralize(form.children, "ребёнок", "ребёнка", "детей")}` : ""}`}/><SummaryRow label="Вариант" value={selectedRoom.title}/><SummaryRow label="Условия" value={`${form.parking ? "парковка" : "без парковки"} · ${form.kitchen ? "кухня нужна" : "кухня не нужна"}${form.extraBed ? " · доп. место" : ""}`}/><div className="summary-total"><span>Ориентировочно за {nights} {pluralize(nights, "ночь", "ночи", "ночей")}</span><strong>{formatPrice(total)}</strong><small>Итог зависит от подтверждения дат и условий владельцем</small></div></div><div className="message-preview"><div className="message-preview-head"><span>Сообщение в WhatsApp</span><button className="copy-button" type="button" onClick={copyMessage}>{copied ? "Скопировано" : "Скопировать"}</button></div><pre>{message}</pre></div></div><a className="button button-whatsapp" href={whatsappHref} target="_blank" rel="noreferrer">Сформировать запрос в WhatsApp <span aria-hidden="true">↗</span></a></div>}
        {error && <p className="form-error" role="alert">{error}</p>}<div className="builder-actions">{step > 1 ? <button className="button button-ghost" type="button" onClick={previousStep}>← Назад</button> : <span/>}{step < 4 ? <button className="button button-dark" type="button" onClick={nextStep}>Дальше <span aria-hidden="true">→</span></button> : <a className="button button-ghost" href="#top">Вернуться к началу ↑</a>}</div>
      </div></div></section>

    <section className="amenities-section section-shell" id="conditions"><div className="section-intro"><div><p className="eyebrow"><span className="eyebrow-dot"/> На территории</p><h2>Всё необходимое<br/>для спокойного отдыха</h2></div><p>Без лишнего списка обещаний — только условия, которые заявлены для «Постоялого двора».</p></div><div className="amenities-grid">{siteConfig.amenities.map((amenity, index) => <article className={`amenity-card ${index === 0 ? "amenity-card-featured" : ""}`} key={amenity.title}><span className="amenity-number">0{index + 1}</span><h3>{amenity.title}</h3><p>{amenity.detail}</p><span className="amenity-arrow" aria-hidden="true">↗</span></article>)}</div><div className="not-included"><span className="not-included-icon">×</span><div><strong>Размещение с домашними животными не предусмотрено</strong><p>Трансфер на странице не заявляем. Если есть особые условия, лучше сразу уточнить их у владельца.</p></div></div></section>
    <section className="gallery-section section-shell"><div className="section-intro"><div><p className="eyebrow"><span className="eyebrow-dot" /> Фотографии объекта</p><h2>Живой двор,<br/>без постановки</h2></div><p>Фотографии из опубликованной карточки «Постоялого двора»: номера, сад, парковка и бытовая зона.</p></div><div className="photo-grid">{siteConfig.photos.map((photo, index) => <figure className={`photo-card photo-card-${index + 1}`} key={photo.src}><img src={photo.src} alt={photo.alt} loading={index === 0 ? "eager" : "lazy"}/><figcaption>{photo.title}</figcaption></figure>)}</div></section>
    <section className="map-section section-shell" id="map"><div className="map-card"><div className="map-copy"><p className="eyebrow"><span className="eyebrow-dot" /> Где находится</p><h2>Небуг,<br/>ул. Приморская, 13А</h2><p>До пляжа около 200 метров. На карте Яндекса отмечено расположение объекта — можно приблизить район и построить маршрут.</p><a className="button button-light" href="https://yandex.ru/maps/?ll=38.9973905%2C44.1641066&amp;z=17&amp;l=map&amp;pt=38.9973905%2C44.1641066%2Cpm2rdm" target="_blank" rel="noreferrer">Открыть карту <span aria-hidden="true">↗</span></a></div><div className="map-frame-wrap"><iframe className="map-frame" title="Карта Яндекса с расположением «Постоялого двора» в Небуге" src="https://yandex.ru/map-widget/v1/?ll=38.9973905%2C44.1641066&amp;z=17&amp;l=map&amp;pt=38.9973905%2C44.1641066%2Cpm2rdm" loading="lazy"/><small className="map-credit">Карта: Яндекс</small></div></div></section>
    <section className="process-section"><div className="section-shell"><div className="section-intro"><div><p className="eyebrow"><span className="eyebrow-dot"/> Как всё проходит</p><h2>Короткий путь<br/>до ясного ответа</h2></div><p>Вы оставляете не абстрактную заявку, а понятный запрос с датами, гостями и условиями.</p></div><div className="process-grid">{[["01", "Укажите даты и состав", "Заезд, выезд, взрослые, дети и дополнительное место."], ["02", "Выберите ориентир", "Подходящий вариант размещения и то, что важно на территории."], ["03", "Получите ответ владельца", "Готовое сообщение откроется в WhatsApp для проверки и отправки."]].map(([number, title, detail]) => <article className="process-card" key={number}><span>{number}</span><h3>{title}</h3><p>{detail}</p></article>)}</div><div className="notice-card"><span className="notice-mark">i</span><p><strong>Цены на странице являются ориентиром</strong><br/>по опубликованным условиям. Наличие и окончательная стоимость подтверждаются владельцем после проверки дат.</p></div></div></section>
    <section className="faq-section section-shell"><div className="section-intro"><div><p className="eyebrow"><span className="eyebrow-dot"/> Частые вопросы</p><h2>Перед поездкой</h2></div><p>Если ответа нет в списке, добавьте вопрос в комментарий — он попадёт владельцу вместе с запросом.</p></div><div className="faq-list">{[["Как далеко до моря?", "До пляжа около 200 метров."], ["Есть ли парковка?", "Да, парковка заявлена на территории. Попросите подтвердить наличие места на ваши даты."], ["Можно ли готовить самостоятельно?", "Да, есть кухня с посудой для самостоятельного приготовления."], ["Можно ли приехать с животными?", "Размещение с домашними животными не предусмотрено."], ["Есть ли дополнительное место?", "Такой запрос можно указать в подборе — возможность дополнительного места подтверждается владельцем."], ["Как узнать актуальную цену?", "Выберите даты: страница покажет ориентир по опубликованным ценам 2026 года. Окончательную стоимость подтвердит владелец."], ["Как забронировать номер?", "Сформируйте сообщение и отправьте его в WhatsApp. Страница не является официальной системой онлайн-бронирования."]].map(([question, answer], index) => <details key={question} open={index === 0}><summary><span>{question}</span><b aria-hidden="true">+</b></summary><p>{answer}</p></details>)}</div></section>
    <section className="final-cta section-shell"><div className="final-cta-inner"><div><p className="eyebrow"><span className="eyebrow-dot"/> Следующий шаг</p><h2>Проверьте наличие<br/>на свои даты</h2><p>Укажите даты и состав гостей — страница подготовит короткий запрос владельцу.</p></div><button className="button button-light" type="button" onClick={goToBuilder}>Узнать наличие в WhatsApp <span aria-hidden="true">↗</span></button><span className="cta-decoration" aria-hidden="true">ПД</span></div></section>
    <footer className="site-footer section-shell"><div className="footer-brand"><span className="brand-mark">ПД</span><div><strong>Постоялый двор</strong><span>Небуг · ул. Приморская, 13А</span></div></div><div className="footer-note"><span>Наличие и итоговая цена подтверждаются владельцем</span><a href={`https://wa.me/${siteConfig.whatsappNumber}`} target="_blank" rel="noreferrer">{siteConfig.whatsappDisplay} ↗</a></div></footer>
    <a className="mobile-sticky-cta" href="#builder" onClick={() => setStep(1)}>Подобрать номер <span aria-hidden="true">↓</span></a>
  </main>;
}

function Counter({ value, min, max, onChange }: { value: number; min: number; max: number; onChange: (value: number) => void }) { return <div className="counter"><button type="button" aria-label="Уменьшить" onClick={() => onChange(Math.max(min, value - 1))} disabled={value <= min}>−</button><strong>{value}</strong><button type="button" aria-label="Увеличить" onClick={() => onChange(Math.min(max, value + 1))} disabled={value >= max}>+</button></div>; }
function Toggle({ checked, onChange, title, detail, symbol }: { checked: boolean; onChange: (value: boolean) => void; title: string; detail: string; symbol: string }) { return <label className={`toggle-card ${checked ? "is-on" : ""}`}><input type="checkbox" aria-label={title} checked={checked} onChange={(event) => onChange(event.target.checked)}/><span className="toggle-symbol">{symbol}</span><span><strong>{title}</strong><small>{detail}</small></span><i className="toggle-indicator"/></label>; }
function SummaryRow({ label, value }: { label: string; value: string }) { return <div className="summary-row"><span>{label}</span><strong>{value}</strong></div>; }
